name = "day04b"
description = "AoC day 4 problemB"
version = "0.1.0-dev"

authors = ["tgv"]
maintainers = ["tgv <email@email.email>"]
maintainers-logins = ["xxx"]
licenses = "custom-custom-NON-AI-APACHE2"
website = ""
tags = []

executables = ["day04b"]

[[depends-on]]
gnatprove = "^15.1.0"
