name = "day04a"
description = "AoC, day 4, problem a"
version = "0.1.0-dev"

authors = ["tgv"]
maintainers = ["tgv <email@email.email>"]
maintainers-logins = ["xxx"]
licenses = "custom-NON-AI-APACHE2"
website = ""
tags = []

executables = ["day04a"]

[[depends-on]]
gnatprove = "^15.1.0"
