name = "day02a"
description = "AoC day2, problem A"
version = "0.1.0-dev"

authors = ["tgv"]
maintainers = ["tgv <email@email.email>"]
maintainers-logins = ["xxx"]
licenses = "custom-NON-AI-APACHE2"
website = ""
tags = []

executables = ["day02a"]

[[depends-on]]
gnatprove = "^15.1.0"
